### ISSUE TITLE
Unbinding mouse causes crash on startup

### ISSUE THREAD

**Issue by zacharied** [nashiora/MusicTheori#6]
If you press escape to unbind a laser control in the input config and leave, future startups of NS crash with this error:
```
System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key was not present in the dictionary.
  Source=mscorlib
  StackTrace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NeuroSonic.IO.KeyboardMouseController.Mouse_Move(Int32 xDelta, Int32 yDelta) in C:\Users\zachd\Code\MusicTheori\GameModes\NeuroSonic\IO\Controller.cs:line 352
   at theori.IO.Mouse.InvokeMove(Int32 mx, Int32 my) in C:\Users\zachd\Code\MusicTheori\music-theori\IO\Mouse.cs:line 59
   at theori.Graphics.Window.Update() in C:\Users\zachd\Code\MusicTheori\music-theori\Graphics\Window.cs:line 169
   at theori.Host.ProgramLoop() in C:\Users\zachd\Code\MusicTheori\music-theori\Host.cs:line 443
   at theori.Host.StartStandalone(GameMode desc, String[] args) in C:\Users\zachd\Code\MusicTheori\music-theori\Host.cs:line 492
   at NeuroSonic.Win32.Program.Main(String[] args) in C:\Users\zachd\Code\MusicTheori\Clients\nsc-Win32\Program.cs:line 109
```

Presumably this could be fixed by having a fallback binding, or just not calling `Mouse_Move` if it's unbound.

**Comment by nashiora** [comment]
Nice find. The entirety of the binding system could use some work, will hopefully get this sorted soon.
